chatproject/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('mobilization.urls')),
]

mobilization/urls.py
from django.urls import path
from .views import PersonsPageView, PersonChangeView, create_person, PersonsDetailView

urlpatterns = [
	path('', PersonsPageView.as_view(), name='home'),
    path('detail/<int:pk>/', PersonsDetailView.as_view(), name='persondetail'),
    path('change/<int:pk>/', PersonChangeView.as_view(), name='personchange'),
    path('new/', create_person, name='personnew')
]
#path('new/', PersonNewView.as_view(), name='personnew')

mobilization/models.py
from django.db import models
from django.urls import reverse



class Index(models.Model):
    name = models.CharField(max_length = 6)
    def __str__(self):
        return self.name
    
class City(models.Model):
    name = models.CharField(max_length = 35)
    def __str__(self):
        return self.name
    
class Street(models.Model):
    name = models.CharField(max_length = 35)
    def __str__(self):
        return self.name
    
class Person(models.Model):
    STATUS_TYPES_CHOISES = [
        ("M", "Мобилизованный"),
        ("W", "Военнослужащий"),
        ("D", "Погибший"),
        ("C", "Комиссованный"),
        ("L", "Пропавший без вести"),
    ]
    firstname = models.CharField("Фамилия", max_length = 35)
    lastname = models.CharField("Имя", max_length = 35)
    fathername = models.CharField("Отчество", max_length = 35)
    birthday = models.DateField("Дата рождения")
    status = models.CharField("Статус военнослужащего", max_length=1, choices=STATUS_TYPES_CHOISES, blank=False)
    statusdate = models.DateField("Дата получения статуса")
    otherdata = models.CharField("Примечание", max_length = 100)


    def __str__(self):
        return self.firstname + " " + self.lastname + " " + self.fathername + " " + str(self.birthday)
    
    def get_absolute_url(self): # new
        return reverse('home')

class FamilyMember(models.Model):
    RELATION_TYPES_CHOISES = [
        ("W", "Жена/Муж"),
        ("M", "Мать/Отец"),
        ("C", "Гражданская жена"),
        ("S", "Сын/Дочь"),
    ]
    SOCIAL_TYPES_CHOISES = [
        ("W", "Трудоспособный"),
        ("P", "Пенсионер"),
        ("D", "Инвалид"),
    ]
    phonenumber = models.CharField("Номер телефона", max_length=14)
    memberfirstname = models.CharField("Фамилия", max_length = 35)
    memberlastname = models.CharField("Имя", max_length = 35)
    memberfathername = models.CharField("Отчество", max_length = 35)
    memberbirthday = models.DateField("Дата рождения")
    social = models.CharField("Социальный статус", max_length=1, choices=SOCIAL_TYPES_CHOISES, blank=False)        
    relation = models.CharField("Семейный статус", max_length=1, choices=RELATION_TYPES_CHOISES, blank=False)
    memberotherdata = models.CharField("Примечание", max_length = 100)
    
    mobilized = models.ForeignKey(Person, on_delete=models.CASCADE)
    
    index = models.ForeignKey(Index, on_delete=models.CASCADE, verbose_name="Почтовый индекс")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="Название населенного пункта")
    street = models.ForeignKey(Street, on_delete=models.CASCADE, verbose_name="Улица")
    building = models.CharField("Номер дома", max_length = 10)
    apartment = models.IntegerField("Номер квартиры")
    
    def __str__(self):
        return self.memberfirstname + " " + self.memberlastname + " " + self.memberfathername + " " + str(self.memberbirthday)

class Needs(models.Model):
    needname = models.CharField(max_length=45)
    memberid = models.ManyToManyField(FamilyMember, through='Protocol')
    def __str__(self):
        return self.needname

class Protocol(models.Model):
    member = models.ForeignKey(FamilyMember, on_delete=models.CASCADE)
    need = models.ForeignKey(Needs, on_delete=models.CASCADE)
    number = models.IntegerField()
    date = models.DateField()
    expiredate = models.DateField() 
    reportdate = models.DateField() 
    complete = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    def __str__(self):
        return str(self.number) + " " + str(self.date) + " " + self.member.memberfirstname + " " + self.member.memberlastname + " " + self.member.memberfathername + " " + str(self.member.memberbirthday) + " " + self.need.needname


# Create your models here.

mobilization/forms.py
from django import forms
from .models import Person, FamilyMember

#class PersonCustomForm(forms.ModelForm):
    #birthday = forms.DateField(input_formats=['%d/%m/%Y'], widget = forms.TextInput(attrs= {'autocomplete': 'off'}))



class PersonCustomForm(forms.ModelForm):
    birthday = forms.DateField(label='Дата рождения', widget=forms.DateInput(format='%d/%m/%Y', attrs={'autocomplete' : 'off'}), input_formats=['%d/%m/%Y'])
    statusdate = forms.DateField(label='Дата получения статуса', widget=forms.DateInput(format='%d/%m/%Y', attrs={'autocomplete' : 'off'}), input_formats=['%d/%m/%Y'])
    class Meta:
        model = Person
        fields = ('firstname', 'lastname', 'fathername', 'birthday', 'status', 'statusdate', 'otherdata')


class FamilyMemberCustomForm(forms.ModelForm):
    memberbirthday = forms.DateField(label='Дата рождения', widget=forms.DateInput(format='%d/%m/%Y', attrs={'autocomplete' : 'off'}), input_formats=['%d/%m/%Y'])
    class Meta:        
        model = FamilyMember
        fields = ('memberfirstname', 'memberlastname', 'memberfathername', 'memberbirthday', 'social', 'relation', 'phonenumber', 'memberotherdata', 'index', 'city', 'street', 'building', 'apartment')

mobilization/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView
from .models import Person, FamilyMember
from .forms import PersonCustomForm, FamilyMemberCustomForm

class PersonsPageView(ListView):
	model = Person
	template_name = "personview.html"
	context_object_name = "persons"

class PersonsDetailView(DetailView):
	model = Person
	template_name = "persondetail.html"
	context_object_name = "person"

class PersonChangeView(UpdateView):
	model = Person
	template_name = "personchange.html"
	fields = ['firstname', 'lastname', 'fathername', 'birthday', 'status', 'statusdate', 'otherdata']

def create_person(request):
	if (request.method == 'POST'):
		p_form = PersonCustomForm(request.POST)
		m_form = FamilyMemberCustomForm(request.POST)
		if (p_form.is_valid() and m_form.is_valid()):
			p_firstname = p_form.cleaned_data['firstname']
			p_lastname = p_form.cleaned_data['lastname']
			p_fathername = p_form.cleaned_data['fathername']
			p_birthday = p_form.cleaned_data['birthday']
			p_status = p_form.cleaned_data['status']
			p_statusdate = p_form.cleaned_data['statusdate']
			p_otherdata = p_form.cleaned_data['otherdata']
			person = Person.objects.create(firstname = p_firstname, lastname = p_lastname, fathername = p_fathername, birthday = p_birthday, status = p_status, statusdate = p_statusdate, otherdata = p_otherdata)
			person.save()


			m_firstname = m_form.cleaned_data['memberfirstname']
			m_lastname = m_form.cleaned_data['memberlastname']
			m_fathername = m_form.cleaned_data['memberfathername']
			m_birthday = m_form.cleaned_data['memberbirthday']
			m_social = m_form.cleaned_data['social']
			m_otherdata = m_form.cleaned_data['memberotherdata']
			m_mobilized = Person.objects.filter(firstname = p_firstname, lastname = p_lastname, fathername = p_fathername, birthday = p_birthday)[0]
			m_relation = m_form.cleaned_data['relation']
			m_phonenumber = m_form.cleaned_data['phonenumber']
			m_index = m_form.cleaned_data['index']
			m_city = m_form.cleaned_data['city']
			m_street = m_form.cleaned_data['street']
			m_building = m_form.cleaned_data['building']
			m_apartment = m_form.cleaned_data['apartment']			
			member = FamilyMember.objects.create(memberfirstname = m_firstname, memberlastname = m_lastname, memberfathername = m_fathername, memberbirthday = m_birthday, social = m_social, relation = m_relation, phonenumber = m_phonenumber, memberotherdata = m_otherdata, mobilized = m_mobilized, index = m_index, city = m_city, street = m_street, building = m_building, apartment = m_apartment)
			member.save()

			return HttpResponseRedirect('/')
	p_form = PersonCustomForm()
	m_form = FamilyMemberCustomForm()
	return render(request, 'personnew.html', {'p_form' : p_form, 'm_form' : m_form})



#class PersonNewView(CreateView):
#	form = PersonCustomForm()
#	model = Person
#	template_name = "personnew.html"
#	fields = ['firstname', 'lastname', 'fathername', 'birthday', 'status', 'statusdate', 'otherdata']

# def home(request):
# 	return HttpResponse('<h1>Главная</h1>')
 
# def about(request):
# 	return HttpResponse('<h1>Наш клуб</h1>')

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Fixed top navbar example В· Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/navbar-fixed/">
    <!--Datepicker-->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <!--EndDatepicker-->


    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'navbar-top-fixed.css' %}" rel="stylesheet">
  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Админка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'personnew' %}">Добавть человека</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>

    </div>
  </div>
</nav>

<div class="container mt-3" style="width: 95%; font-size: 14px;">

    
    {% block content %}

    {% endblock content %}  

</div>


    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

templates/membernew.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>

<!-- <script>
    $(function () {
      $("#id_birthday").datepicker({
        format:'dd/mm/yyyy',
      });
    });
    $(function () {
      $("#id_statusdate").datepicker({
        format:'dd/mm/yyyy',
      });
    });
</script> -->

{% endblock content %}

templates/personchange.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>


{% endblock content %}

templates/persondetail.html
{% extends 'base.html' %}
{% block content %}

    <p> {{ person.firstname }} </p>
    <p> {{ person.lastname }} </p>
    <p> {{ person.fathername }} </p>
    <p> {{ person.birthday }} </p>
    <p> {{ person.status }} </p>
    <a href="{% url 'personchange' person.pk %}">Изменить</a>
{% endblock content %}

templates/personnew.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<form action="" method="post" class="card p-3 mt-5">
    {% csrf_token %}
    <h3>Информация о представителе семьи</h3>
    <div class="row">
      <div class="col-3">{{m_form.memberfirstname|as_crispy_field}}</div>
      <div class="col-3">{{m_form.memberlastname|as_crispy_field}}</div>
      <div class="col-3">{{m_form.memberfathername|as_crispy_field}}</div>
      <div class="col-3">{{m_form.memberbirthday|as_crispy_field}}</div>
    </div>
    <div class="row">
      <div class="col-3">{{m_form.social|as_crispy_field}}</div>
      <div class="col-3">{{m_form.relation|as_crispy_field}}</div>
      <div class="col-3">{{m_form.phonenumber|as_crispy_field}}</div>
      <div class="col-3">{{m_form.memberotherdata|as_crispy_field}}</div>
    </div>
    <h5>Адрес регистрации</h5>
    <div class="row">
      <div class="col-2">{{m_form.index|as_crispy_field}}</div>
      <div class="col-3">{{m_form.city|as_crispy_field}}</div>
      <div class="col-3">{{m_form.street|as_crispy_field}}</div>
      <div class="col-2">{{m_form.building|as_crispy_field}}</div>
      <div class="col-2">{{m_form.apartment|as_crispy_field}}</div>
    </div>      
    <h3>Информация о военнослужащем</h3>
    <div class="row">
      <div class="col-3">{{p_form.firstname|as_crispy_field}}</div>
      <div class="col-3">{{p_form.lastname|as_crispy_field}}</div>
      <div class="col-3">{{p_form.fathername|as_crispy_field}}</div>
      <div class="col-3">{{p_form.birthday|as_crispy_field}}</div>
    </div>
    <div class="row">
      <div class="col-4">{{p_form.status|as_crispy_field}}</div>
      <div class="col-4">{{p_form.statusdate|as_crispy_field}}</div>
      <div class="col-4">{{p_form.otherdata|as_crispy_field}}</div>
    </div>

    <input type="submit" value="Сохранить" class="btn btn-primary mt-3">
</form>

<script>
    $(function () {
      $("#id_birthday").datepicker({
        format:'dd/mm/yyyy',
      });
    });
    $(function () {
      $("#id_memberbirthday").datepicker({
        format:'dd/mm/yyyy',
      });
    });
    $(function () {
      $("#id_statusdate").datepicker({
        format:'dd/mm/yyyy',
      });
    });
</script>

{% endblock content %}

templates/personview.html
{% extends 'base.html' %}
{% block content %}
<!-- <form class="card p-3 mt-5"> -->
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
<!-- </form> -->
<ul class="list-group">
{% for person in persons %}

    <li class="list-group-item"><a href="{% url 'persondetail' person.pk %}"> {{ person.firstname }} {{ person.lastname }} {{ person.fathername }}  {{ person.birthday }}</a></li>


    


{% endfor %}
</ul>
{% endblock content %}